# using duckduckgo_search, because DuckDuckGo does not collect or share personal
# information. That its privacy policy, it prevents search leakage by default.  
# read more about it at https://duckduckgo.com/privacy
from duckduckgo_search import ddg_suggestions, ddg

# escape function causes param to be rendered as text, preventing the execution of 
# injection script in the user’s browser or the in the api request.
from markupsafe import escape

# using duckduckgo_search, because DuckDuckGo does not collect or share personal
# information. That its privacy policy, it prevents search leakage by default.  
# read more about it at https://duckduckgo.com/privacy
#for feed in feed_categories:
#    results = ddg_suggestions(feed, region='br-pt')
#    for result in results:    
#        print("\"",result['phrase'],"\",")

class BapDDG():
    def phrase_to_search(self,value):
        self.phrase_to_results = ddg(value, region='br-pt', safesearch='on', time='y', max_results=5)
        self.list_suggestions = []

        for phrase in self.phrase_to_results:
            new_phrase = { 
                    "description":phrase['body'],
                    "title":phrase['title'],
                    "source":phrase['href'],
                    "categorie":"none" }

            self.list_suggestions.append(new_phrase)

    def __init__(self,debugMode=False,export=False):
        if (debugMode):
            for i in test_subjects_for_research():
                self.phrase_to_search(value=i)
        else:
            print("Debug Mode is offline")

        if (export):
            # total time 14 minutes
            with open("bap_ddg_results.txt", "w") as f:
                for row in self.list_suggestions:
                    for key, value in row.items():
                        f.write("{}; ".format(value))
                    f.write("\n")
        else:
            print("Export is disable")

something = BapDDG()

def test_subjects_for_research():
    return [" autoesporte ",
" autoesporte g1 ",
" auto esporte globo ",
" autoesporte domingo ",
" autoesporte passo fundo ",
" autoesporte qual comprar 2022 ",
" autoesporte mclaren ",
" auto esporte revista ",
" autoesporte g1 ",
" auto esporte globo ",
" auto esporte globoplay ",
" auto esporte globo domingo ",
" autoesporte domingo ",
" auto esporte revista ",
" autosport revista ",
" autoesporte g1 ",
" auto esporte globo ",
" auto esporte globoplay ",
" auto esporte globo domingo ",
" auto esporte globoplay ",
" auto esporte globo domingo ",
" auto esporte de hoje domingo ",
" auto esporte globo hoje ",
" auto esporte de domingo ",
" auto esporte na globo ",
" auto esporte globo ontem ",
" programa auto esporte globo ",
" auto esporte globo play ",
" autoesporte domingo ",
" autoesporte passo fundo ",
" auto esporte passo fundo telefone ",
" auto esporte passo fundo rs ",
" auto esporte passo fundo centro ",
" autoesporte mclaren ",
" autosport mclaren f1 forum ",
" autosport mclaren f1 forum ",
" automotive forums mclaren f1 ",
" mclaren f1 official site ",
" mclaren f1 sports car ",
" mclaren f1 official website ",
" mclaren f1 in car ",
" mclaren f1 car 2017 ",
" mclaren f1 logo 2019 ",
" auto esporte revista ",
" autosport revista ",
" autosport revista ",
" auto esporte revista ",
" tecnologia ",
" tecnologia da informação ",
" tecnologia assistiva ",
" tecnologia 5g ",
" tecnologia na educação ",
" tecnologia sinônimo ",
" tecnologias disruptivas ",
" tecnologia e inovação ",
" tecnologia da informação ",
" tecnologia da informação faculdade ",
" tecnologia da informação e comunicação ",
" tecnologia da informação curso ",
" tecnologia da informação salário ",
" tecnologia da informação ead ",
" tecnologia da informação pdf ",
" tecnologia da informação banco do brasil ",
" tecnologia assistiva ",
" tecnologia assistiva na educação ",
" tecnologia assistiva exemplos ",
" tecnologia assistiva na educação inclusiva ",
" tecnologia assistiva para surdos ",
" tecnologia assistiva para cegos ",
" tecnologia assistiva pdf ",
" tecnologia assistiva ta ",
" tecnologia 5g ",
" tecnologia 5g en colombia ",
" tecnología 5g pdf ",
" tecnologia 5g en ecuador ",
" tecnologia 5g en peru ",
" tecnologia 5g come funziona ",
" tecnología 5g beneficios ",
" tecnologia 5g mexico ",
" tecnologia na educação ",
" tecnologia na educação infantil ",
" tecnologia na educação artigo ",
" tecnologia na educação redação ",
" tecnologia na educação pdf ",
" tecnologia na educação problema ou solução ",
" tecnologia na educação inclusiva ",
" tecnologia na educação brasileira ",
" tecnologia sinônimo ",
" sinonimo de tecnologia ",
" sinônimo de tecnologia ",
" sinônimos de tecnologia ",
" sinonimo di tecnologia ",
" tecnologia de punta sinonimo ",
" tecnologias disruptivas ",
" tecnologias disruptivas exemplos ",
" tecnologias disruptivas pdf ",
" tecnologías disruptivas ejemplos ",
" tecnologias disruptivas en mexico ",
" tecnologias disruptivas significado ",
" tecnologias disruptivas” ",
" tecnologias disruptivas uber ",
" tecnologia e inovação ",
" tecnologia e inovação na educação ",
" tecnologia e inovação novo ensino médio ",
" tecnologia e inovação atividades ",
" tecnologia e inovação pdf ",
" tecnologia e inovação 5 ano ",
" tecnologia e inovação 9 ano ",
" tecnologia e inovação resumo ",
" tecnologia da informação ",
" tecnologia da informação e comunicação ",
" tecnologia da informação faculdade ",
" tecnologia da informação curso ",
" tecnologia da informação salário ",
" tecnologia da informação ead ",
" tecnologia da informação pdf ",
" tecnologia da informação banco do brasil ",
" tecnologia da informação faculdade ",
" tecnologia da informação faculdade preço ",
" tecnologia da informação faculdade publica ",
" tecnologia da informação faculdade ead ",
" tecnologia da informação faculdade manaus ",
" faculdade gestão da tecnologia da informação ",
" melhor faculdade de tecnologia da informação ",
" faculdade tecnologia da informação presencial ",
" tecnologia da informação e comunicação ",
" tecnologia da informação e comunicação senai ",
" tecnologia da informação e comunicação tic ",
" tecnologia da informação e comunicação pdf ",
" tecnologia da informação e comunicação enem ",
" tecnologia da informação e comunicação resumo ",
" tecnologia da informação e comunicação oque é ",
" tecnologia da informação e comunicação curso ",
" tecnologia da informação curso ",
" tecnologia da informação curso gratuito ",
" tecnologia da informação curso técnico ",
" tecnologia da informação curso online ",
" tecnologia da informação curso gratis ",
" curso de tecnologia da informação gratuito ",
" tecnologia da informação tempo de curso ",
" curso de tecnologia da informação presencial ",
" tecnologia da informação banco do brasil ",
" banco do brasil tecnologia e serviços ",
" informática banco do brasil ",
" tecnologias sociais banco do brasil ",
" tecnologia da informação no brasil ",
" agente de tecnologia banco do brasil ",
" informações banco do brasil ",
" tecnologia em banco de dados ",
" tecnologia assistiva ",
" tecnologia assistiva na educação ",
" tecnologia assistiva exemplos ",
" tecnologia assistiva na educação inclusiva ",
" tecnologia assistiva para surdos ",
" tecnologia assistiva para cegos ",
" tecnologia assistiva pdf ",
" tecnologia assistiva ta ",
" tecnologia assistiva na educação ",
" tecnologia assistiva na educação inclusiva ",
" tecnologia assistiva na educação exemplos ",
" tecnologia assistiva na educação especial ",
" tecnologia assistiva na educação especial pdf ",
" tecnologia assistiva na educação infantil ",
" tecnologia assistiva na escola ",
" tecnologia assistiva aplicada à educação ",
" tecnologia assistiva exemplos ",
" tecnologia assistiva para idosos exemplos ",
" tecnologia assistiva na educação inclusiva ",
" a inclusão da tecnologia na educação infantil ",
" inclusão e tecnologias assistivas ",
" tecnologia e didattica inclusiva ",
" tecnologia assistiva na educação ",
" tecnologia assistiva na educação especial ",
" tecnologia assistiva na educação especial pdf ",
" tecnologia assistiva para a educação ",
" tecnologia assistiva para surdos ",
" tecnologia assistiva surdos ",
" tecnologias acessíveis para surdos ",
" a tecnologia a favor dos surdos ",
" surdos e as tecnologias ",
" recursos tecnológicos para surdos ",
" aparelho de telecomunicação para surdos ",
" desafios para formação de surdos no brasil ",
" tecnologia assistiva para cegos ",
" sobre a tecnologia assistiva ",
" tecnologia assistiva em portugal ",
" tecnologia assistiva ou ajuda técnica ",
" tecnologia assistiva para a educação ",
" quais as tecnologias assistivas ",
" tecnologia assistiva nas empresas ",
" que é tecnologia assistiva ",
" tecnologia 5g ",
" tecnologia 5g en colombia ",
" tecnología 5g pdf ",
" tecnologia 5g en ecuador ",
" tecnologia 5g en peru ",
" tecnologia 5g come funziona ",
" tecnología 5g beneficios ",
" tecnologia 5g mexico ",
" tecnología 5g beneficios ",
" tecnologia 5g mexico ",
" tecnologia na educação ",
" tecnologia na educação infantil ",
" tecnologia na educação artigo ",
" tecnologia na educação redação ",
" tecnologia na educação pdf ",
" tecnologia na educação problema ou solução ",
" tecnologia na educação inclusiva ",
" tecnologia na educação brasileira ",
" tecnologia na educação infantil ",
" tecnologia na educação infantil pdf ",
" tecnologia na educação infantil artigo ",
" tecnologia na educação infantil bncc ",
" projeto sobre tecnologia na educação infantil ",
" projeto de tecnologia na educação infantil ",
" projeto tecnologia na educação infantil ",
" tecnologia digital na educação infantil ",
" tecnologia na educação artigo ",
" tecnologia na educação artigos scielo ",
" tecnologia na educação artigo científico ",
" tecnologia na escola artigo ",
" sobre a tecnologia na educação ",
" tecnologia na educação pdf ",
" a tecnologia na educação ",
" pdf sobre tecnologia na educação ",
" tecnologia na educação redação ",
" redação sobre tecnologia na educação ",
" o impacto da tecnologia na educação redação ",
" redação sobre a tecnologia ",
" tecnologia nas escolas redação ",
" redação sobre tecnologia na atualidade ",
" tecnologia tema de redação ",
" tema de redação sobre tecnologia ",
" tecnologia na educação inclusiva ",
" tecnologia assistiva na educação inclusiva ",
" tecnologia assistiva educação inclusiva ",
" a inclusão da tecnologia na educação infantil ",
" tecnologia e didattica inclusiva ",
" tics na educação inclusiva ",
" tudo sobre educação inclusiva ",
" trabalho de educação inclusiva ",
" tecnologia na educação brasileira ",
" o uso das tecnologias na educação brasileira ",
" sobre a tecnologia na educação ",
" a tecnologia na educação ",
" o que é tecnologia na educação ",
" tecnologias na educação básica ",
" tecnologia na educação pdf ",
" uso da tecnologia na educação ",
" tecnologias digitais ",
" tecnologias digitais na educação ",
" tecnologias digitais exemplos ",
" tecnologias digitais educativas ",
" tecnologias digitais na educação pdf ",
" tecnologias digitais da informação ",
" tecnologias digitais curso ",
" tecnologias digitais e segurança ",
" tecnologias digitais na educação ",
" tecnologias digitais na educação pdf ",
" tecnologias digitais na educação ufc ",
" tecnologias digitais na educação básica ",
" tecnologias digitais na educação mec ",
" tecnologias digitais na educação ppt ",
" tecnologias digitais na educação infantil ",
" curso tecnologias digitais na educação ",
" tecnologias digitais exemplos ",
" tecnologias digitais educativas ",
" tecnologias digitais na educação pdf ",
" uso das tecnologias digitais na educação ",
" o uso das tecnologias digitais na educação ",
" as tecnologias digitais na educação do brasil ",
" tecnologias na educação pdf ",
" tecnologias digitais na educação infantil ",
" artigo sobre tecnologias digitais na escola ",
" tecnologias digitais aplicadas à educação ",
" tecnologias digitais da informação ",
" tecnologias digitais de informação ",
" tecnologias digitais o que é ",
" quais são as tecnologias digitais ",
" o que são tecnologias digitais ",
" tecnologia digital da informação ",
" tecnologias digitais e educação ",
" conceito de tecnologias digitais ",
" tecnologias digitais curso ",
" tecnologias digitais e segurança ",
" digital tecnologia e segurança ",
" tecnologias digitais da informação ",
" tecnologias digitais de informação ",
" tecnologias digitais e educação ",
" tecnologias digitais o que são ",
" tecnologias digitais o que é ",
" o maior acesso as tecnologias digitais ",
" tecnologia social ",
" tecnologia social exemplos ",
" tecnologia social pdf ",
" tecnologia social conceito ",
" tecnología social ejemplos ",
" tecnologia social no brasil ",
" tecnologia social da memória ",
" tecnologia social comercio electronico ",
" tecnologia social exemplos ",
" tecnologia social pdf ",
" tecnologia social conceito ",
" tecnologia social no brasil ",
" tecnologia social o que é ",
" o que tecnologia social ",
" o que e tecnologia social ",
" oq e tecnologia social ",
" o que é uma tecnologia social ",
" exemplos de tecnologia social ",
" exemplo de tecnologia social ",
" tecnologia social da memória ",
" o que é memória social ",
" o que e memoria social ",
" memória social e memória coletiva ",
" quais as tecnologias utilizadas em memórias ",
" revista de memoria social ",
" desenvolvimento da memória de trabalho ",
" memória e identidade social ",
" tecnologia social comercio electronico ",
" comercio electrónico y redes sociales ",
" el comercio electrónico y las redes sociales ",
" comercio electrónico en las redes sociales ",
" comercio electrónico social ejemplos ",
" sistema de comercio electronico ",
" sistemas de comercio electrónico ",
" el comercio electronico es ",
" economia ",
" economia circular ",
" economia de energia ",
" economia uol ",
" economia do brasil ",
" economia brasileira ",
" economia verde ",
" economia criativa ",
" economia circular ",
" economia circular conceito ",
" economia circular exemplos ",
" economia circular no brasil ",
" economía circular ellen macarthur ",
" economia circular e logística reversa ",
" economia circular ppt ",
" economia circulara ",
" economia uol ",
" economia uol cotações ",
" economia uol dolar ",
" economia uol últimas ",
" economia uol ultimas noticias ",
" economia uol dolar turismo ",
" economia uol euro ",
" economia uol bolsa ",
" economia de energia ",
" economia de energia do pc ",
" economia de energia monitor ",
" economia de energia windows 10 ",
" economia de energia usb ",
" economia de energia elétrica ",
" economia de energia notebook ",
" economia de energia wmm ",
" economia regional ",
" economia regional e urbana ",
" economia regionale ",
" economia regional definicion ",
" economía regional pdf ",
" economia regional uel ",
" economia regionale unive ",
" economia regionale banca d'italia ",
" economia do brasil ",
" economia do brasil 2023 ",
" economia do brasil 2022 ",
" economia do brasil atualmente ",
" economia do brasil no governo lula ",
" economia do brasil colonial ",
" economia do brasil atualmente 2022 ",
" economia do brasil 2021 ",
" economia brasileira ",
" economia brasileira 2023 ",
" economia brasileira 2022 ",
" economia brasileira atual ",
" economia brasileira 2015 ",
" economia brasileira contemporânea ",
" economia brasileira contemporânea pdf ",
" economia brasileira resumo ",
" economia criativa ",
" economia criativa conceito ",
" economia criativa exemplos ",
" economia criativa no brasil ",
" economia criativa pdf ",
" economia criativa sebrae ",
" economia criativa e inovação ",
" economia criativa livro ",
" economia circular ",
" economia circular conceito ",
" economia circular exemplos ",
" economia circular no brasil ",
" economía circular ellen macarthur ",
" economia circular e logística reversa ",
" economia circular ppt ",
" economia circulara ",
" economia circular conceito ",
" essência do conceito de economia circular ",
" economia circular exemplos ",
" economía circular ejemplos de empresas ",
" exemplos de economia circular no brasil ",
" exemplos de economia circular em portugal ",
" economia circular no brasil ",
" economia circular no brasil exemplos ",
" oq e economia circular ",
" oq é economia circular ",
" economia circular no mundo ",
" o que economia circular ",
" contribuições da economia circular ",
" economia circular o que é ",
" economia circular e logística reversa ",
" economia circular y logistica inversa ",
" oq e logística reversa ",
" reverse logistics circular economy ",
" política de logística reversa ",
" oq é logística reversa ",
" o que e logística reversa ",
" reverse logistics and circular economy ",
" economia de energia ",
" economia de energia do pc ",
" economia de energia monitor ",
" economia de energia windows 10 ",
" economia de energia usb ",
" economia de energia elétrica ",
" economia de energia notebook ",
" economia de energia wmm ",
" economia de energia do pc ",
" modo economia de energia no pc ",
" modo de economia de energia pc ",
" modo economia de energia pc ",
" consumo de energia do pc ",
" ver consumo de energia do pc ",
" computador entrando em economia de energia ",
" consumo de energia de um pc ",
" economia de energia monitor ",
" monitor entrando em economia de energia ",
" economia energia monitor ",
" monitor de consumo de energia pc ",
" monitoramento de consumo de energia ",
" monitor de energia pc ",
" monitor gestão de energia ",
" monitorear consumo de energia pc ",
" economia de energia elétrica ",
" economia de energia eletrica ",
" dicas de economia de energia elétrica ",
" imagens de economia de energia elétrica ",
" economia de água e energia elétrica ",
" economia de energia com energia solar ",
" opções de economia de energia ",
" economia e consumo de energia ",
" economia uol ",
" economia uol cotações ",
" economia uol dolar ",
" economia uol últimas ",
" economia uol ultimas noticias ",
" economia uol dolar turismo ",
" economia uol euro ",
" economia uol bolsa ",
" economia uol cotações ",
" economia uol cotacoes ",
" economia uol dolar ",
" economia uol dolar turismo ",
" cotação dolar turismo venda hoje uol economia ",
" economia uol últimas ",
" uol economia últimas notícias ",
" economia uol ultimas noticias ",
" ultimas noticias de economia ",
" ultimas noticias da economia ",
" últimas notícias da economia ",
" noticias sobre a economia ",
" noticias sobre la economia ",
" noticias recientes de economia ",
" noticias de la economia ",
" economia uol dolar turismo ",
" cotação dolar turismo venda hoje uol economia ",
" uol cotacao dolar turismo ",
" uol cotação dolar turismo ",
" uol dolar turismo hoje ",
" uol cotação dólar turismo ",
" dolar turismo valor economico ",
" uol dólar turismo hoje ",
" economia uol euro ",
" economia uol bolsa ",
" economia do brasil ",
" economia do brasil 2023 ",
" economia do brasil 2022 ",
" economia do brasil atualmente ",
" economia do brasil no governo lula ",
" economia do brasil colonial ",
" economia do brasil atualmente 2022 ",
" economia do brasil 2021 ",
" economia do brasil atualmente ",
" economia do brasil atualmente 2022 ",
" economia do brasil atualmente 2021 ",
" como está a economia do brasil atualmente ",
" como vai a economia do brasil ",
" economia do brasil resumo ",
" economia do brasil colonial ",
" economia do brasil colonial resumo ",
" economia do período colonial ",
" economia do brasil colônia ",
" em que se baseava a economia colonial ",
" o que era a economia colonial ",
" atividades econômicas do brasil colonial ",
" base da economia colonial ",
" economia brasileira ",
" economia brasileira 2023 ",
" economia brasileira 2022 ",
" economia brasileira atual ",
" economia brasileira 2015 ",
" economia brasileira contemporânea ",
" economia brasileira contemporânea pdf ",
" economia brasileira resumo ",
" economia brasileira contemporânea ",
" economia brasileira contemporânea pdf ",
" economia brasileira contemporânea gremaud pdf ",
" economia brasileira contemporânea gremaud ",
" economia brasileira contemporânea giambiagi ",
" economia brasileira contemporânea livro ",
" economia brasileira contemporanea ",
" economia brasileira · contemporanea ",
" economia verde ",
" economia verde pdf ",
" economia verde empresas ",
" economia verde conceito ",
" economia verde definicion ",
" economia verde peru ",
" economia verde onu ",
" economía verde y azul ",
" economia verde empresas ",
" economia verde conceito ",
" conceito de economia verde ",
" economia verde definicion ",
" economia verde onu ",
" economia criativa ",
" economia criativa conceito ",
" economia criativa exemplos ",
" economia criativa no brasil ",
" economia criativa pdf ",
" economia criativa sebrae ",
" economia criativa e inovação ",
" economia criativa livro ",
" economia criativa conceito ",
" economia criativa conceito pdf ",
" economia criativa exemplos ",
" economia criativa no brasil ",
" do que trata a economia criativa ",
" economia criativa o que é ",
" oq e economia criativa ",
" oq é economia criativa ",
" o que economia criativa ",
" o que e economia criativa ",
" exemplos de economia criativa ",
" economia criativa sebrae ",
" economia criativa sebrae rn ",
" economia criativa e inovação ",
" oq e economia criativa ",
" oq é economia criativa ",
" o que e economia criativa ",
" economia criativa o que é ",
" o que economia criativa ",
" exemplos de economia criativa ",
" inovação e criatividade nas empresas ",
" economia criativa livro ",
" turismocity ",
" turismo ",
" turismo em foco ",
" turismo rural ",
" turismo no brasil ",
" turismo sp ",
" turismo cultural ",
" turismo sustentável ",
" turismo rural ",
" turismo rural no brasil ",
" turismo rural portugal ",
" turismo rural pirineo ",
" turismo rural navarra ",
" turismo rural en el valle del jerte ",
" turismo rural alentejo ",
" turismo rurale ",
" turismo no brasil ",
" turismo no brasil redação ",
" turismo no brasil 2023 ",
" turismo no brasil 2022 ",
" turismo no brasil dados ",
" turismo no brasil resumo ",
" turismo no brasil ibge ",
" turismo no brasil pdf ",
" turismo cultural ",
" turismo culturale ",
" turismo cultural pdf ",
" turismo cultural en honduras ",
" turismo cultural definición ",
" turismo culturale italiano ",
" turismo cultural omt ",
" turismo cultural en españa ",
" turismo sustentável ",
" turismo sustentável redação ",
" turismo sustentável pdf ",
" turismo sustentável em portugal ",
" turismo sustentável exemplos ",
" turismo sustentável no brasil ",
" turismo sustentável definição ",
" turismo sustentável açores ",
" turismo religioso ",
" turismo religioso no brasil ",
" turismo religioso pdf ",
" turismo religioso definicion ",
" turismo religioso in italia ",
" turismo religioso em portugal ",
" turismo religioso definição ",
" turismo religioso en italia ",
" turismo ecologico ",
" turismo ecologico ucr ",
" turismo ecológico definición ",
" turismo ecologico en españa ",
" turismo ecologico en mexico ",
" turismo ecologico panama ",
" turismo ecologico en ecuador ",
" turismo ecologico ucr plan de estudios ",
" turismo rural ",
" turismo rural no brasil ",
" turismo rural portugal ",
" turismo rural pirineo ",
" turismo rural navarra ",
" turismo rural en el valle del jerte ",
" turismo rural alentejo ",
" turismo rurale ",
" turismo rural no brasil ",
" oque é turismo rural ",
" turismo rural o que é ",
" turismo rural no rs ",
" turismo rural no mundo ",
" oq e turismo rural ",
" o que e turismo rural ",
" o que é o turismo rural ",
" turismo rural portugal ",
" turismo rural portugal com piscina ",
" turismo rural portugal norte ",
" turismo rural portugal crianças ",
" turismo rural em portugal ",
" turismo rural norte de portugal ",
" turismo rural centro de portugal ",
" turismo no brasil ",
" turismo no brasil redação ",
" turismo no brasil 2023 ",
" turismo no brasil 2022 ",
" turismo no brasil dados ",
" turismo no brasil resumo ",
" turismo no brasil ibge ",
" turismo no brasil pdf ",
" turismo no brasil redação ",
" redação sobre turismo no brasil ",
" incentivo ao turismo no brasil redação ",
" turismo no brasil pdf ",
" redação sobre turismo espacial ",
" tudo sobre turismo no brasil ",
" o turismo no brasil ",
" turismo no brasil dados ",
" crescimento do turismo no brasil ",
" turismo no brasil pdf ",
" tudo sobre turismo no brasil ",
" desenvolvimento do turismo no brasil ",
" o turismo no brasil ",
" setor de turismo no brasil ",
" o setor de turismo no brasil ",
" turismo no brasil resumo ",
" tudo sobre turismo no brasil ",
" o turismo no brasil ",
" turismo no brasil pdf ",
" turismo no sul do brasil ",
" importancia do turismo no brasil ",
" importância do turismo no brasil ",
" tipos de turismo no brasil ",
" turismo no brasil ibge ",
" economia do turismo ibge ",
" cidades do brasil ibge ",
" área do brasil ibge ",
" habitantes do brasil ibge ",
" ibge regiões do brasil ",
" educação no brasil ibge ",
" mapa do brasil ibge ",
" turismo sustentável em portugal ",
" exemplos de turismo sustentável em portugal ",
" turismo sustentável portugal ",
" turismo sustentável no brasil ",
" o que é turismo sustentável ",
" turismo sustentável no mundo ",
" o que é o turismo sustentável ",
" exemplos de turismo sustentável ",
" turismo sustentável exemplos ",
" turismo sustentável exemplos em portugal ",
" exemplos de turismo sustentável em portugal ",
" turismo sustentavel no brasil ",
" turismo sustentável no brasil ",
" turismo sustentável no mundo ",
" o que é turismo sustentável ",
" turismo sustentável em portugal ",
" turismo sustentável exemplos em portugal ",
" o que é o turismo sustentável ",
" exemplos de turismo sustentável ",
" turismo sustentável definição ",
" turismo sustentável definição omt ",
" turismo sustentável açores "]
